site_name: pyPhotometry
site_url: https://pyphotometry.readthedocs.io/
site_description: Open source, Python based, fiber photometry data acquisition.
site_author: Thomas Akam

theme:
    name: readthedocs

repo_url: https://github.com/pyPhotometry/docs

nav:
- Home: index.md
- User Guide:
    - Graphical user interface (GUI): user-guide/graphical-user-interface.md
    - Hardware: user-guide/hardware.md
    - Importing data: user-guide/importing-data.md
    - Troubleshooting: user-guide/troubleshooting.md
- Resources:
    - Optical Components: resources/optical-components.md

- About:
    - Release Notes: about/release-notes.md
    - License: about/license.md

copyright: Copyright &copy; 2018-2020 <a href="/release-notes/">Thomas Akam</a>.
